#!/bin/bash
cd "$(dirname "$0")"
echo - Building JavaScript

cat shebangAdder.txt ../js/extraFunctions.js ../js/network/neuralNetwork.js ../js/collision.js ../js/entity.js ../js/trainer.js ../js/game.js app.js > execute.js

echo \|-------------------\|
echo \| Finished Building \|
echo \|-------------------\|
